# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'test01' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for test01

  target 'test01Tests' do
    inherit! :search_paths
pod 'AppsFlyerFramework'
    # Pods for testing
  end

  target 'test01UITests' do
    # Pods for testing
  end

end
